spring.application.name=aero-cloud-backend
server.port=8080
server.address=0.0.0.0

spring.h2.console.enabled=true
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:drone_db
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.username=user
spring.datasource.password=